Revert "skip some alembic migrations for sqlite"
This reverts commit e23eba1ba81cd04473cf4d2c9d3b93f396cb5b73.

TypeError: Error when calling the metaclass bases
build_fulltext() takes exactly 2 arguments (1 given)

Change-Id: Ic8859b2b5668a03d3e2ef6f479c5f8c0ec36effd